### ISSUE TITLE
Wrong Decoding With Bytes

### ISSUE THREAD

**Issue by nazavod777** [fubuloubu/eth-abi#238]
### What happened?

```python
from eth_abi import decode
from web3.auto import w3

print(decode(
    ['(address,uint256,address,uint256,uint256,bytes)'],
    w3.to_bytes(
        hexstr='00000000000000000000000005c4deac8c16980c1e9a880ebb2c7a457bca1970000000000000000000000000000000000000000000000000000000003c336080000000000000000000000000dac17f958d2ee523a2206206994597c13d831ec70000000000000000000000000000000000000000000000000000000066bb4590000000000000000000000000000000000000000000000000000000000000d66100000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000000419ecd6a6c409f7775dbb51fc627398e12f2a6b2fb459036a57f261982bafb2e9e1fe810c82ca53cefed39f0bd49ea5afe9a73ca3887ab726610a1a17135323b691b00000000000000000000000000000000000000000000000000000000000000'
    ),
    strict=False
))
```
eth_abi.exceptions.InvalidPointer: Invalid pointer in tuple at location 0 in payload

but if change `['(address,uint256,address,uint256,uint256,bytes)'],` to `['(address,uint256,address,uint256,uint256,bytes32)'],` (adding bytes length - 32) - works
also if change types to list - `['address', 'uint256', 'address', 'uint256', 'uint256', 'bytes']` - works too, but not with '(address,uint256,address,uint256,uint256,bytes)' format

fix it pls

### Code that produced the error

```python
from eth_abi import decode
from web3.auto import w3

print(decode(
    ['(address,uint256,address,uint256,uint256,bytes)'],
    w3.to_bytes(
        hexstr='00000000000000000000000005c4deac8c16980c1e9a880ebb2c7a457bca1970000000000000000000000000000000000000000000000000000000003c336080000000000000000000000000dac17f958d2ee523a2206206994597c13d831ec70000000000000000000000000000000000000000000000000000000066bb4590000000000000000000000000000000000000000000000000000000000000d66100000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000000419ecd6a6c409f7775dbb51fc627398e12f2a6b2fb459036a57f261982bafb2e9e1fe810c82ca53cefed39f0bd49ea5afe9a73ca3887ab726610a1a17135323b691b00000000000000000000000000000000000000000000000000000000000000'
    ),
    strict=False
))
```

### Full error output

```shell
Traceback (most recent call last):
  File "/test2.py", line 4, in <module>
    print(decode(
          ^^^^^^^
  File "/home//.local/lib/python3.11/site-packages/eth_abi/codec.py", line 162, in decode
    return cast(Tuple[Any, ...], decoder(stream))
                                 ^^^^^^^^^^^^^^^
  File "/home//.local/lib/python3.11/site-packages/eth_abi/decoding.py", line 131, in __call__
    return self.decode(stream)
           ^^^^^^^^^^^^^^^^^^^
  File "/home//.local/lib/python3.11/site-packages/eth_utils/functional.py", line 47, in inner
    return callback(fn(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home//.local/lib/python3.11/site-packages/eth_abi/decoding.py", line 224, in decode
    self.validate_pointers(stream)
  File "/home//.local/lib/python3.11/site-packages/eth_abi/decoding.py", line 211, in validate_pointers
    raise InvalidPointer(
eth_abi.exceptions.InvalidPointer: Invalid pointer in tuple at location 0 in payload
```

### eth-abi Version

5.1.0

### Python Version

3.11.6

### Operating System

linux

### Output from `pip freeze`

```shell
aiodns==3.2.0
aiofiles==24.1.0
aiohappyeyeballs==2.3.5
aiohttp==3.10.2
aiohttp-proxy==0.1.2
aiohttp_socks==0.9.0
aiosignal==1.3.1
aiosocks==0.2.6
annotated-types==0.7.0
apturl==0.5.2
async-timeout==4.0.3
attrs==24.2.0
beautifulsoup4==4.12.3
better-proxy==1.1.0
bitarray==2.9.2
blinker==1.4
Brlapi==0.8.3
Brotli==1.1.0
bs4==0.0.2
cached-property==1.5.2
certifi==2020.6.20
cffi==1.17.0
chardet==4.0.0
charset-normalizer==3.3.2
ckzg==1.0.2
click==8.0.3
colorama==0.4.4
command-not-found==0.3
cryptography==3.4.8
cupshelpers==1.0
cytoolz==0.12.3
dbus-python==1.2.18
defer==1.0.6
distro==1.7.0
distro-info==1.1+ubuntu0.2
eth-account==0.11.2
eth-bloom==3.0.1
eth-hash==0.7.0
eth-keyfile==0.8.1
eth-keys==0.5.1
eth-rlp==1.0.1
eth-typing==4.4.0
eth-utils==4.1.1
eth_abi==5.1.0
flashbots==2.0.0
frozenlist==1.4.1
hexbytes==0.3.1
httplib2==0.20.2
idna==3.3
importlib-metadata==4.6.4
jeepney==0.7.1
jsonschema==4.23.0
jsonschema-specifications==2023.12.1
keyring==23.5.0
language-selector==0.1
launchpadlib==1.10.16
lazr.restfulclient==0.14.4
lazr.uri==1.0.6
loguru==0.7.2
louis==3.20.0
lru-dict==1.2.0
lxml==5.3.0
macaroonbakery==1.3.1
more-itertools==8.10.0
multidict==6.0.5
netifaces==0.11.0
oauthlib==3.2.0
olefile==0.46
parsimonious==0.10.0
pexpect==4.8.0
Pillow==9.0.1
protobuf==5.27.3
ptyprocess==0.7.0
py-ecc==7.0.1
py-evm==0.10.1b1
pycairo==1.20.1
pycares==4.4.0
pycparser==2.22
pycryptodome==3.20.0
pycups==2.0.1
pydantic==2.8.2
pydantic_core==2.20.1
PyGObject==3.42.1
PyJWT==2.3.0
pymacaroons==0.13.0
PyNaCl==1.5.0
pyparsing==2.4.7
pyRFC3339==1.1
PySocks==1.7.1
python-apt==2.4.0+ubuntu3
python-dateutil==2.8.1
python-debian==0.1.43+ubuntu1.1
python-socks==2.5.0
pytz==2022.1
pyunormalize==15.1.0
pyuseragents==1.0.5
pyxdg==0.27
PyYAML==5.4.1
redis==5.0.8
referencing==0.35.1
regex==2024.7.24
reportlab==3.6.8
requests==2.32.3
rlp==4.0.1
rpds-py==0.20.0
screen-resolution-extra==0.0.0
SecretStorage==3.3.1
six==1.16.0
sortedcontainers==2.4.0
soupsieve==2.5
systemd-python==234
toolz==0.12.1
trie==3.0.1
typing_extensions==4.12.2
ubuntu-drivers-common==0.0.0
ubuntu-pro-client==8001
ufw==0.36.1
unattended-upgrades==0.1
urllib3==1.26.5
uvloop==0.19.0
wadllib==1.3.6
web3==6.20.1
websockets==12.0
xdg==5
xkit==0.0.0
yarl==1.9.4
zipp==1.0.0
```

**Comment by fselmo** [comment]
You're trying to decode a tuple type when you define it as `"(element1, element2, ...)"`. These are single elements therefore need to be decoded as such, same as in Solidity: `["element1", "element2", ...]`. It seems you've already realized that decoding via a list gives you the expected value. Please [refer to the docs](https://eth-abi.readthedocs.io/en/stable/decoding.html#decoding-abi-values) for more info.

**Comment by nazavod777** [comment]
> You're trying to decode a tuple type when you define it as `"(element1, element2, ...)"`. These are single elements therefore need to be decoded as such, same as in Solidity: `["element1", "element2", ...]`. It seems you've already realized that decoding via a list gives you the expected value. Please [refer to the docs](https://eth-abi.readthedocs.io/en/stable/decoding.html#decoding-abi-values) for more info.

so why `['(address,uint256,address,uint256,uint256,bytes32)']` working? this error is related to the bytes length, not the types format

**Comment by fselmo** [comment]
This is specific to this particular case. It won't work every time. Here's a comprehensive explanation from chatGPT.

---

To break down and understand how this encoded bytestring can be decoded both as individual elements and as a struct, let's first dissect the structure of the encoding:

### ABI Encoding Breakdown:
Given the `encoded` string and knowing the types involved:

```python
struct = "(address,uint256,address,uint256,uint256,bytes32)"
individual_types = ['address', 'uint256', 'address', 'uint256', 'uint256', 'bytes']
```

### The Encoded Bytestring:
```
"0x00000000000000000000000005c4deac8c16980c1e9a880ebb2c7a457bca1970"  # address (20 bytes)
"0000000000000000000000000000000000000000000000000000000003c33608"   # uint256 (value: 63202440)
"000000000000000000000000dac17f958d2ee523a2206206994597c13d831ec7"   # address (20 bytes)
"0000000000000000000000000000000000000000000000000000000066bb4590"   # uint256 (value: 1071820112)
"000000000000000000000000000000000000000000000000000000000000d661"   # uint256 (value: 548945)
"00000000000000000000000000000000000000000000000000000000000000c0"   # offset to `bytes`
"0000000000000000000000000000000000000000000000000000000000000004"   # length of `bytes` (32 bytes)
"9ecd6a6c409f7775dbb51fc627398e12f2a6b2fb459036a57f261982bafb2e9e"   # bytes[0:32]
"1fe810c82ca53cefed39f0bd49ea5afe9a73ca3887ab726610a1a17135323b69"   # continuation of bytes (not relevant for bytes32)
```

### Decoding as Individual Elements:
When you decode this string using the individual types:
1. **`address`**: The first 32 bytes are `0x00000000000000000000000005c4deac8c16980c1e9a880ebb2c7a457bca1970`, which represents the address `0x05c4deac8c16980c1e9a880ebb2c7a457bca1970`.
2. **`uint256`**: The next 32 bytes `0x0000000000000000000000000000000000000000000000000000000003c33608` represent the integer `63202440`.
3. **`address`**: The next 32 bytes `0x000000000000000000000000dac17f958d2ee523a2206206994597c13d831ec7` represent the address `0xdac17f958d2ee523a2206206994597c13d831ec7`.
4. **`uint256`**: The next 32 bytes `0x0000000000000000000000000000000000000000000000000000000066bb4590` represent the integer `1071820112`.
5. **`uint256`**: The next 32 bytes `0x000000000000000000000000000000000000000000000000000000000000d661` represent the integer `548945`.
6. **`bytes`**: The next 32 bytes are `0x00000000000000000000000000000000000000000000000000000000000000c0`, which is an offset pointing to where the actual `bytes` data starts. This points to `0x0000000000000000000000000000000000000000000000000000000000000004`, indicating the start of the data for the `bytes` field. This offset is then followed by the actual data (which is 32 bytes).

### Decoding as a Struct:
When you decode this string using the struct `(address,uint256,address,uint256,uint256,bytes32)`:
1. **`address`**: Same as above.
2. **`uint256`**: Same as above.
3. **`address`**: Same as above.
4. **`uint256`**: Same as above.
5. **`uint256`**: Same as above.
6. **`bytes32`**: Here, the last 32 bytes `9ecd6a6c409f7775dbb51fc627398e12f2a6b2fb459036a57f261982bafb2e9e` are interpreted directly as `bytes32`, representing the 32 bytes of fixed data.

### Why Both Decoding Methods Work:
- **Fixed-Size Nature**: The `bytes32` in the struct can correctly interpret the final 32 bytes of data because `bytes32` is a fixed-size type. The encoded `bytes` data happens to be exactly 32 bytes long, so the ABI encoding places this data at the location where `bytes32` expects to find its value.

- **ABI Encoding Compatibility**: ABI encoding does not differentiate between `bytes` (with 32 bytes of data) and `bytes32` because the encoded data looks identical once the length and offset are handled. Thus, whether you decode the final 32 bytes as `bytes32` or as the content of a `bytes` array, the result is the same.

### Conclusion:
In this specific case, since the `bytes` data happens to be exactly 32 bytes, it fits perfectly within what is expected for a `bytes32`. This allows both the struct decoding (with `bytes32`) and individual element decoding (with `bytes`) to work seamlessly. The struct decoding doesn't interfere with the expected data, as it aligns correctly with the encoded values.
